name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: swift-actions/setup-swift@v2
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test -v